export const provincias = [
  {
    nombre: "Buenos Aires",
    localidades: [
      "La Plata",
      "Mar del Plata",
      "Bahía Blanca",
      "Tandil",
      "Quilmes",
      "Lomas de Zamora",
      "Avellaneda",
      "Lanús",
      "Morón",
      "San Isidro",
      "Vicente López",
      "San Fernando",
      "Tres de Febrero",
      "Ituzaingó",
      "Tigre",
      "San Miguel",
      "Esteban Echeverría",
      "Florencio Varela",
      "Berazategui",
      "San Martín",
      "José C. Paz",
      "Malvinas Argentinas",
      "Ezeiza",
      "Merlo",
      "Moreno",
      "Pilar",
      "Hurlingham",
      "General Pueyrredón",
      "Olavarría",
      "Zárate",
      "Campana",
      "Pergamino",
      "Junín",
      "Necochea",
      "Chivilcoy",
      "Balcarce",
      "Azul",
      "Luján",
      "San Nicolás",
      "General Rodríguez",
      "Almirante Brown",
      "Cañuelas",
      "Brandsen",
      "Marcos Paz",
      "Escobar",
      "Navarro",
      "Monte",
      "Lobos",
      "Mercedes",
      "Baradero",
      "Saladillo",
      "Lincoln",
      "San Pedro",
      "Tigre",
      "Ramallo",
    ],
  },
  {
    nombre: "Catamarca",
    localidades: [],
  },
  {
    nombre: "Chaco",
    localidades: [],
  },
  {
    nombre: "Chubut",
    localidades: [],
  },
  {
    nombre: "Córdoba",
    localidades: [],
  },
  {
    nombre: "Corrientes",
    localidades: [],
  },
  {
    nombre: "Entre Ríos",
    localidades: [],
  },
  {
    nombre: "Formosa",
    localidades: [],
  },
  {
    nombre: "Jujuy",
    localidades: [],
  },
  {
    nombre: "La Pampa",
    localidades: [],
  },
  {
    nombre: "La Rioja",
    localidades: [],
  },
  {
    nombre: "Mendoza",
    localidades: [],
  },
  {
    nombre: "Misiones",
    localidades: [],
  },
  {
    nombre: "Neuquén",
    localidades: [],
  },
  {
    nombre: "Río Negro",
    localidades: [],
  },
  {
    nombre: "Salta",
    localidades: [],
  },
  {
    nombre: "San Juan",
    localidades: [],
  },
  {
    nombre: "San Luis",
    localidades: [],
  },
  {
    nombre: "Santa Cruz",
    localidades: [],
  },
  {
    nombre: "Santa Fe",
    localidades: [],
  },
  {
    nombre: "Santiago del Estero",
    localidades: [],
  },
  {
    nombre: "Tierra del Fuego",
    localidades: [],
  },
  {
    nombre: "Tucumán",
    localidades: [],
  },
  {
    nombre: "CABA",
    localidades: [
      "Agronomia",
      "Almagro",
      "Barracas",
      "Balvanera",
      "Belgrano",
      "Boedo",
      "Caballito",
      "Chacarita",
      "Coghlan",
      "Colegiales",
      "Constitución",
      "Flores",
      "Floresta",
      "La Boca",
      "Liniers",
      "Mataderos",
      "Monserrat",
      "Monte Castro",
      "Nueva Pompeya",
      "Palermo",
      "Parque Avellaneda",
      "Parque Chacabuco",
      "Parque Chas",
      "Parque Patricios",
      "Paternal",
      "Puerto Madero",
      "Recoleta",
      "Retiro",
      "Saavedra",
      "San Cristóbal",
      "San Nicolás",
      "San Telmo",
      "Vélez Sarsfield",
      "Versalles",
      "Villa Crespo",
      "Villa del Parque",
      "Villa Devoto",
      "Villa General Mitre",
      "Villa Lugano",
      "Villa Luro",
      "Villa Ortúzar",
      "Villa Pueyrredón",
      "Villa Real",
      "Villa Riachuelo",
      "Villa Santa Rita",
      "Villa Soldati",
      "Villa Urquiza",
    ],
  },
];
